# Site
repository: eldorajan/
favicon: images/favicon.ico

# Personal info
name: Eldo Rajan
title: Senior Tech Lead - Quality Assurance
email: eldorajan@gmail.com
website: www.github.com/eldorajan/

# Social links
twitter_username: eldorajan87
github_username:  eldorajan
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: eldorajan
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Agile QA automation expert with 13+ years of experience across Cyber Security/Cloud Security/Educational/Social domains with various Fortune 500 companies like Symantec/Yahoo.
  
  Expertise in developing highly scalable automation frameworks for REST API/Browser/Mobile/Desktop based applications and CI/CD pipeline solutions which can be deployed in Docker/Kubernetes platform or native environments.

  Proficient in developing high volume regression tests to cover application functionality across multiple browser/os platforms.
     

  

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software quality engineering some of my other interests and hobbies are:
   - Cycling
   - Rock climbing
   - Gaming

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
