title: Eldo Rajan's Testing Playground
description: Rantings of automation full stack engineer passionate about building software solutions to make testing done easier and integrate machine learning into the mix
google_analytics: 
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
